apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-jupyter
  labels:
    app: tensorflow-jupyter
spec:
  containers:
  - name: tensorflow-container
    image: tensorflow/tensorflow:latest-py3
    ports:
      - containerPort: 8888
    command: ["jupyter", "notebook"]
    args:
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--allow-root"
      - "--no-browser"
